force-app/main/default/objects/Log_Handler__mdt/Log_Handler__mdt.object-meta.xml
<CustomObject>
    <label>Log Handler</label>
    <pluralLabel>Log Handlers</pluralLabel>
</CustomObject>

force-app/main/default/objects/Log_Handler__mdt/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log_Handler__mdt/fields/Logger__c.field-meta.xml
<CustomField>
    <fullName>Logger__c</fullName>
    <label>Logger</label>
    <referenceTo>Logger__mdt</referenceTo>
    <relationshipLabel>Log Handlers</relationshipLabel>
    <relationshipName>Log_Handlers</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Log_Handler__mdt/fields/Namespace__c.field-meta.xml
<CustomField>
    <fullName>Namespace__c</fullName>
    <label>Namespace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Handler__mdt/fields/Setting__c.field-meta.xml
<CustomField>
    <fullName>Setting__c</fullName>
    <label>Setting</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Handler__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Logger__mdt/fields/Namespace__c.field-meta.xml
<CustomField>
    <fullName>Namespace__c</fullName>
    <label>Namespace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Logger__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Logger Implementation Type of ILogger interface</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LoggerSettingsService.cls
public class LoggerSettingsService {

    public static final String DEFAULT_LOGGER_SETTING_NAME = 'DEFAULT_LOGGER';

    public static Logger__mdt getDefaultLoggerSetting() {
        List<Logger__mdt> settings = [
            SELECT Is_Active__c, DeveloperName, Namespace__c, Type__c
            FROM Logger__mdt
            WHERE DeveloperName = :LoggerSettingsService.DEFAULT_LOGGER_SETTING_NAME
            LIMIT 1
        ];
        return settings.isEmpty() ? null : settings.get(0);
    }

    public static Logger__mdt getDefaultActiveLoggerSetting() {
        Logger__mdt setting = getDefaultLoggerSetting();
        return setting.Is_Active__c ? setting : null;
    }

    public static List<Log_Handler__mdt> getDefaultLoggerHandlersSettings() {
        List<Log_Handler__mdt> settings = [
            SELECT DeveloperName, Setting__c, Namespace__c, Type__c, Is_Active__c, Logger__r.Is_Active__c
            FROM Log_Handler__mdt
            WHERE Logger__r.DeveloperName = :LoggerSettingsService.DEFAULT_LOGGER_SETTING_NAME
        ];
        return settings;
    }

    public static List<Log_Handler__mdt> getDefaultActiveLoggerHandlersSettings() {
        List<Log_Handler__mdt> settings = getDefaultLoggerHandlersSettings();

        List<Log_Handler__mdt> activeLogHandlerSettings = new List<Log_Handler__mdt>();

        for (Log_Handler__mdt logHandlerSetting : settings) {
            if (logHandlerSetting.Is_Active__c == true && logHandlerSetting.Logger__r.Is_Active__c == true) {
                activeLogHandlerSettings.add(logHandlerSetting);
            }
        }

        return activeLogHandlerSettings;
    }

}