force-app/main/default/objects/Log_Handler__mdt/Log_Handler__mdt.object-meta.xml
<CustomObject>
    <label>Log Handler</label>
    <pluralLabel>Log Handlers</pluralLabel>
</CustomObject>

force-app/main/default/objects/Log_Handler__mdt/fields/Namespace__c.field-meta.xml
<CustomField>
    <fullName>Namespace__c</fullName>
    <label>Namespace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Handler__mdt/fields/Setting__c.field-meta.xml
<CustomField>
    <fullName>Setting__c</fullName>
    <label>Setting</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Handler__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LogHandlersFactory.cls
public class LogHandlersFactory {

    public List<ILogHandler> getHandlers() {

        List<ILogHandler> logHandlers = new List<ILogHandler>();

        if (Test.isRunningTest()) {
            return logHandlers;
        }

        List<Log_Handler__mdt> settings = LoggerSettingsService.getDefaultActiveLoggerHandlersSettings();

        for (Log_Handler__mdt setting : settings) {

            Map<String, Object> settingMap;
            try {
                settingMap = (Map<String, Object>) JSON.deserializeUntyped(setting.Setting__c);
            } catch (Exception ex) {
                System.debug(ex.getMessage() + ' ' + ex.getStackTraceString());
                settingMap = new Map<String, Object>();
            }

            try {
                Type handlerType = Type.forName(
                    setting.Namespace__c,
                    setting.Type__c
                );
                ILogHandler logHandler = (ILogHandler) handlerType.newInstance();
                logHandler.setSettings(settingMap);

                logHandlers.add(logHandler);
            } catch (Exception ex) {
                System.debug(ex.getMessage() + ' ' + ex.getStackTraceString());
            }
        }

        return logHandlers;
    }

}