force-app/main/default/objects/Log__e/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/PlatformEventLoggerImpl.cls
public class PlatformEventLoggerImpl extends LoggerImpl {

    public override Log publish(Log logToPublish) {

        if (logToPublish.isEmpty()) {
            return logToPublish;
        }

        Database.SaveResult saveResult = EventBus.publish(
            new Log__e(
                Details__c = JSON.serialize(logToPublish.getDetails(), false),
                Data__c = JSON.serialize(logToPublish.getLogItems(), false)
            )
        );

        return logToPublish;
    }

}